### ISSUE TITLE
User Guide | end to end, need Forseti instructions

### ISSUE THREAD

**Issue by alexsgoogle** [forseti-security/config-validator#20]
The end to end covers nicely up to the end of Terraform, however, it doesn't go into how to test Forseti manually:

/home/ubuntu/forseti-security/install/gcp/scripts/run_forseti.sh

**Comment by t12g** [comment]
@joecheuk Do you see any issues with mentioning /home/ubuntu/forseti-security/install/gcp/scripts/run_forseti.sh in user guide? I don't see that in the current Forseti docs...

**Comment by joecheuk** [comment]
depending on the size of the environment, it is recommended for the user to let the cron job run instead of manually running it because the cronjob can overlap with the run_forseti.sh script if it takes a while to run and it will make it very slow if both of them are running at the same time (R/W to the sql instance) and also theres a concern when both runs are R/W from the FCV instance user will be getting duplicate data

**Comment by alexsgoogle** [comment]
What if we include this in the end-to-end section only with the caveat that Joe mentions and the recommendation that this test should only be for sandbox environments with limited scope

**Comment by t12g** [comment]
sgtm. @joecheuk wdyt?

**Comment by briantkennedy** [comment]
no longer in scope
