### ISSUE TITLE
Update ancestry path to plural

### ISSUE THREAD

**Issue by morgante** [forseti-security/config-validator#74]
We should update the ancestry path to use plural resource types (ex. `organizations/999/folders/232/projects/111`).

Work involved would be:
- [x] Update core FCV code to assume plural ancestry paths
- [x] Add a simple helper to pluralize input ancestry paths
- [ ] Update policy-library samples/test cases to use plural paths

**Comment by yukinying** [comment]
Since FCV is already accepting ancestors, I suggest adding a transient logic to make the behavior consistent. What I mean is that, if ancestors is provided, the ancestry path would contain plural because of the following:

https://github.com/forseti-security/config-validator/blob/87b4ae546420814b2a6766a1b4569278f5e1627e/pkg/gcv/validator.go#L234-L242

This is already breaking the behavior if callee is sending ancestors. Before the plural fixes are done, perhaps we should have a temporary fix on ancestryPath function to make the behavior be consistent?

**Comment by briantkennedy** [comment]
FCV now accepts both plural and non plural for match target/exclude.  In the future, we plan to warn on non-plural then eventually reject it.
